version: "3.9"
services:
  s1_host0:
    image: kennethreitz/httpbin
    ports: 
      - "9090:80"
    networks:
      - service1-network
  s1_host1:
    image: kennethreitz/httpbin
    ports: 
      - "9091:80"
    networks:
      - service1-network
  s1_host2:
    image: kennethreitz/httpbin
    ports: 
      - "9092:80"
    networks:
      - service1-network
  s2_host0:
    image: kennethreitz/httpbin
    ports: 
      - "9093:80"
    networks:
      - service2-network
  s2_host1:
    image: kennethreitz/httpbin
    ports: 
      - "9094:80"
    networks:
      - service2-network
  s2_host2:
    image: kennethreitz/httpbin
    ports: 
      - "9095:80"
    networks:
      - service2-network
  app:
    build: 
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - service1-network
      - service2-network

networks:
  service1-network:
    driver: bridge
  service2-network:
    driver: bridge