proxy:
  lbPolicy: "ROUND_ROBIN"
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      hosts:
        - address: "http://localhost"
          port: 9090
        - address: "upstream-service-b"
          port: 9090  